version: "3.9"

services: 
  doom-bot:
    build: "."
    container_name: "doom-bot"
    restart: "always"
    environment:
      - TOKEN: /run/secrets/token

secrets: 
  token:
    file: "./credentials/token.txt"