version: "3.9"

services: 
  lavalink:
    image: fredboat/lavalink:master
    container_name: lavalink
    restart: always
    ports:
      - 2333:2333
    volumes: 
      - ./lavalink-config/application.yml:/opt/Lavalink/application.yml
  doom-bot:
    build: .
    container_name: doom-bot
    restart: always
    secrets:
      - token
      - lavalink-passwd
    depends_on:
      - lavalink-doom 

secrets: 
  token:
    file: ./credentials/token.txt
  lavalink-passwd:
    file: ./credentials/lavalink-passwd.txt