version: "3.9"

services: 
  lavalink-doom:
    image: "fredboat/lavalink:master"
    container_name: "lavalink-doom"
    restart: "always"
    network_mode: host 
    ports:
      - "127.0.0.1:2333:2333"
    volumes: 
      - "./lavalink-config/application.yml:/opt/Lavalink/application.yml"
  doom-bot:
    build: "."
    container_name: "doom-bot"
    restart: "always"
    secrets:
      - token
    depends_on:
      - lavalink-doom 

secrets: 
  token:
    file: ./credentials/token.txt