version: "3.9"

services: 
  doom-bot:
    build: "."
    container_name: "doom-bot"
    restart: "always"
    secrets:
      - token
  lavalink-doom:
    image: "fredboat/lavalink"
    container_name: "lavalink-doom"
    restart: "always"
    ports:
      - "2333:2333"
    volumes: 
      - "./lavalink-config/:/opt/Lavalink/"

secrets: 
  token:
    file: ./credentials/token.txt